e_service/urls.py
from django.urls import path,include,reverse
from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.conf import settings
# from django.conf.urls.static import static

# from django.shortcuts import redirect

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# def redirect_to_home(request):
#     return redirect(reverse('admin:index'))

@login_required
def dashboard(request):
    return render(request, 'acceptance/dashboard.html')

urlpatterns = [
    path('managers/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('accounts.urls')), 
    # path('check/', include('check_cordinates.urls')), 
    # path("about/", flatpages_views.flatpage, {"url": "/about/"}, name="about"),
    # path('pa/', include('pa.urls')), 
    path('hr/', include('hr.urls')), 
    path('it/', include('it.urls')), 
    path('fleet/', include('fleet.urls')), 
    path('sandog/', include('sandog.urls')), 
    path('needs/', include('needs_request.urls')),
    
    # path('help/', include('help_request.urls')), 
    path('', include('hr_bot.urls')), 
    path('', dashboard, name='acceptance_home'),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('surveys/', include('hr_employee_survey.urls')),
    path(r'treewidget/', include('treewidget.urls'))
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns = [path('app/', include(urlpatterns))]

#     from django.urls import reverse
#     from django.shortcuts import redirect
#     def redirect_to_home(request):
#         return redirect(reverse('profile:home'))
    
#     urlpatterns.append(
#         path('', redirect_to_home)
#     )

hr/urls.py
from django.urls import path

from django.conf import settings

from .views import Badalat, CheckPayroll, FargKhosomat,Khosomat, KhosomatPlusMokaf2, M2moria, MajlisEl2daraMokaf2View, Mobashara, Modir3amBadalatView, Modir3amKhosomatView, Modir3amMokaf2View, Mokaf2,FargBadalat, Mokaf2MajlisWzara, Ta3agodMosimiMokaf2, Ta3agodMosimiMoratab, Tasoia, Wi7datMosa3idaMokaf2tFarigMoratab,Wi7datMosa3idaMokaf2t

app_name = "hr"
urlpatterns = [                                                        
    path('payroll/badalat', Badalat.as_view(), name='payroll_badalat'),
    path('payroll/khosomat', Khosomat.as_view(), name='payroll_khosomat'),
    path('payroll/check_payroll', CheckPayroll.as_view(), name='payroll_check'),
    path('payroll/mobashara', Mobashara.as_view(), name='payroll_mobashara'),
    path('payroll/mokaf2', Mokaf2.as_view(), name='payroll_mokaf2'),
    path('payroll/mokaf2_majlis', Mokaf2MajlisWzara.as_view(), name='payroll_mokaf2_majlis'),
    path('payroll/moratab_mokaf2', KhosomatPlusMokaf2.as_view(), name='payroll_moratab_mokaf2'),
    path('payroll/m2moria', M2moria.as_view(), name='payroll_m2moria'),

    path('payroll/diff_badalat', FargBadalat.as_view(), name='payroll_diff_badalat'),
    path('payroll/diff_khosomat', FargKhosomat.as_view(), name='payroll_diff_khosomat'),

    path('payroll/wi7dat_mosa3ida_farg_moratab', Wi7datMosa3idaMokaf2tFarigMoratab.as_view(), name='payroll_wi7dat_mosa3ida_farg_moratab'),
    path('payroll/wi7dat_mosa3ida_mokaf2', Wi7datMosa3idaMokaf2t.as_view(), name='payroll_wi7dat_mosa3ida_mokaf2'),

    path('payroll/ta3agod_mosimi_moratab', Ta3agodMosimiMoratab.as_view(), name='payroll_ta3agod_mosimi_moratab'),
    path('payroll/ta3agod_mosimi_mokaf2', Ta3agodMosimiMokaf2.as_view(), name='payroll_ta3agod_mosimi_mokaf2'),

    path('payroll/majlis_el2dara_mokaf2', MajlisEl2daraMokaf2View.as_view(), name='payroll_majlis_el2dara_mokaf2'),

    path('payroll/modir_3am_badalat', Modir3amBadalatView.as_view(), name='payroll_modir_3am_badalat'),
    path('payroll/modir_3am_khosomat', Modir3amKhosomatView.as_view(), name='payroll_modir_3am_khosomat'),
    path('payroll/modir_3am_mokaf2', Modir3amMokaf2View.as_view(), name='payroll_modir_3am_mokaf2'),
    path('payroll/tasoia', Tasoia.as_view(), name='payroll_tasoia'),

]

hr_employee_survey/urls.py
from django.urls import path
from . import views
app_name = "surveys"
urlpatterns = [
    path("emergency_survey/", views.emergency_form, name="emergency_form"),
    path('get_employee_name/', views.get_employees_under_manager, name='get_employees_under_manager'),
    path('structure_survey/', views.survey_view, name='survey_form'),
    path('survey_thank_you/', views.survey_thank_you, name='survey_thank_you'),
    path('employee_list/', views.employee_list, name='employee_list'),
    path('create_employee/', views.employee_create, name='employee_create'),
    path('list/', views.survey_list_view, name='survey_list'), 
    path('submissions/', views.submission_list_view, name='submission_list'),
    path('employee-sim/add/', views.employee_sim_create, name='employee_sim_add'),
    path('employee_simcard/', views.employee_sim_list_view, name='employee_sim_list'),

]

hr_employee_survey/models.py
from django.db import models
from hr.models import EmployeeBasic,MosamaWazifi,HikalWazifi
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]
WARNING_CHOICES = [(i, str(i)) for i in range(0, 6)]
GENERAL_RATING = [(i, str(i)) for i in range(0, 6)]
PERCENTAGE_CHOICES= []
RATING_MAPPING = {
    "excellent": 5, "very_good": 4, "good": 3, "acceptable": 2, "weak": 1,
}

ASKING_CHOICES  = [(i, str(i)) for i in range(0, 2)]

RATING_FIELDS = [
    'attendance_discipline', 'follow_instructions', 'task_responsibility',
    'teamwork', 'communication', 'main_tasks_quality', 'extra_tasks',
    'work_pressure', 'policies_commitment', 'creativity'
]

class Employee_Data_Emergency(models.Model):
   
    name = models.CharField(
        max_length=255, 
        verbose_name="اسم الموظف"
    )
    email = models.EmailField(
        null=True, 
        blank=True,
        verbose_name="البريد الإلكتروني"
    )

    direct_manager_email = models.EmailField(
        verbose_name="بريد المدير المباشر",
        null=True, 
        blank=True
    ) 

    job_title = models.CharField(
        max_length=255, 
        verbose_name="المسمى الوظيفي "
    )  


    edara_3ama = models.CharField(
        max_length=255, 
        null=True, 
        blank=True,
        verbose_name="الادارة العامة"
    ) 

    class Meta:
        verbose_name = "بيانات موظف لتقييم 2025"


class Employee_Sim_Card(models.Model):
   
    name = models.CharField(
        max_length=255, 
        verbose_name="اسم الموظف"
    )

    sim_number = models.CharField(
        max_length=15,
        verbose_name="رقم الشريحة ",unique=True,
    )

    department = models.CharField(
       blank=True, null=True,max_length=255,  
       verbose_name=_("الإدارة / القسم")
    ) 

    email = models.EmailField(
        null=True, 
        blank=True,
        verbose_name="البريد الإلكتروني"
    )

    class Meta:
        verbose_name = "بيانات شريحة موظف 2025"


class EmergencyEvaluation(models.Model):
    
    employee_code = models.IntegerField(verbose_name="كود الموظف")
    employee_name = models.CharField(max_length=150,verbose_name="اسم الموظف  ")
    email = models.CharField(max_length=150, verbose_name=" البريد الالكتروني للموظف ")
    
    job_title = models.CharField(max_length=100,verbose_name=" المسمى الوظيفي")
    direct_manager = models.CharField(null=True, blank=True,max_length=100, verbose_name=" المدير المباشر")
    direct_manager_email = models.CharField(null=True, blank=True,max_length=100, verbose_name=" ")
    period_from = models.DateField(verbose_name="من")
    period_to = models.DateField(verbose_name="الي" )
    created_at = models.DateTimeField(auto_now_add=True , verbose_name="تم الانشاء في ",null=True, blank=True)

    attendance_discipline = models.IntegerField(choices=RATING_CHOICES, verbose_name=" الالتزام بالحضور والانضباط")
    follow_instructions = models.IntegerField(choices=RATING_CHOICES, verbose_name="احترام التعليمات ")
    task_responsibility = models.IntegerField(choices=RATING_CHOICES, verbose_name=" تحمل المسؤولية وتعدد المهام")
    teamwork = models.IntegerField(choices=RATING_CHOICES, verbose_name=" التعاون والعمل ضمن فريق")
    communication = models.IntegerField(choices=RATING_CHOICES, verbose_name=" التواصل الفعال")

    main_tasks_quality = models.IntegerField(choices=RATING_CHOICES,verbose_name="انجاز المهام الرئيسية بجودة وكفاءة ")
    extra_tasks = models.IntegerField(choices=RATING_CHOICES,verbose_name=" إنجاز المهام الاضافية خارج التوصيف ")
    work_pressure = models.IntegerField(choices=RATING_CHOICES, verbose_name=" القدرة علي التكيف مع ضغط العمل ")
    policies_commitment = models.IntegerField(choices=RATING_CHOICES, verbose_name=" الالتزام بالاجراءات والسياسات")
    creativity = models.IntegerField(choices=RATING_CHOICES, verbose_name="الابداع في تقديم الحلول ")

    overall_performance = models.CharField(null=True, blank=True,max_length=20 ,verbose_name=" مستوي الانجاز العام")
    emergency_response = models.IntegerField( choices=RATING_CHOICES, verbose_name=" مدي الاستجابة لعمل لطبيعة العمل ")
    coverage_percentage = models.IntegerField( choices=RATING_CHOICES, verbose_name=" نسبة تغطية الفجوة")

    strengths = models.TextField(verbose_name=" نقاط القوة لدى الموظف ")
    challenges = models.TextField(verbose_name=" التحديات")
    training_needs = models.TextField(verbose_name=" الاحتياجات التدريبية ")
    manager_notes = models.TextField(verbose_name="تعليق المدير المباشر")

    average_attendance = models.IntegerField( choices=GENERAL_RATING, null=True, blank=True,verbose_name= "متوسط نسبة الحصور والانصراف")
    attendance_punctnality = models.IntegerField( choices=GENERAL_RATING, null=True, blank=True,verbose_name="الالتزام بمواعيد الدوام")
    violation_count = models.IntegerField(choices=WARNING_CHOICES, null=True, blank=True,verbose_name="عدد المخالفات الادارية المسجلة")
    warnings_count = models.IntegerField(choices=WARNING_CHOICES, null=True, blank=True,verbose_name="عدد الانزارات او التنبيهات الادارية")
        
    employee_effective = models.IntegerField(null=True, blank=True, choices=ASKING_CHOICES,verbose_name="هل ترى أن الموظف كان فاعلاً ")
    recommendations_continue = models.IntegerField(null=True, blank=True, choices=ASKING_CHOICES,verbose_name="هل توصي باستمراره ضمن فريق العمل ")
    substantive_note = models.TextField(null=True, blank=True,verbose_name="هل هنالك ملاحظات جوهرية على أدائه ")
    manager_average_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name="متوسط تقييم المدير ")
 
    def clean(self):
        super().clean()
        if self.period_from and self.period_to:
            if self.period_to < self.period_from:
                raise ValidationError({
                    'period_to': 'تاريخ النهاية يجب أن يكون مساوياً أو بعد تاريخ البداية.'
                })
                
    def _get_numerical_score_from_hr(self, field_name):
        value = getattr(self, field_name)

        if value is None or value == '':
            return None
            
        if field_name in ['violation_count', 'warnings_count']:
            try:
                val = int(value)
                if val == 0: return 5
                elif val == 1: return 4
                elif val == 2: return 3
                elif val == 3: return 2
                else: return 1
            except:
                return None
        return None

    def _calculate_manager_average(self):
        total_sum = 0
        count = 0
        for field_name in RATING_FIELDS:
            value = getattr(self, field_name)
            if value is not None and value != '':
                try:
                    total_sum += int(value)
                    count += 1
                except ValueError:
                    continue 
        return round( (total_sum / count), 2 ) if count > 0 else None   

    def _hr_data_is_complete(self):
        hr_fields = ['average_attendance', 'attendance_punctnality', 'violation_count', 'warnings_count']
        for field in hr_fields:
            value = getattr(self, field)
            if value is None or value == '':
                return False
        return True
    
    def _calculate_combined_average(self):
        total_sum = 0
        count = 0
        
        for field_name in RATING_FIELDS:
            value = getattr(self, field_name)
            if value is not None and value != '':
                try:
                    total_sum += int(value)
                    count += 1
                except ValueError:
                    continue 
                    
        hr_fields = ['average_attendance', 'attendance_punctnality', 'violation_count', 'warnings_count']
        if self._hr_data_is_complete():
            for field_name in hr_fields:
                hr_score = self._get_numerical_score_from_hr(field_name)
                if hr_score is not None:
                    total_sum += hr_score
                    count += 1
        
        return round((total_sum / count), 2) if count > 0 else None


    def _get_overall_rating_key(self, average):
        if average is None: return None
        
        if average >= 4.21:
            return "excellent"
        
        elif average >= 3.41:
            return "very_good"
            
        elif average >= 2.61:
            return "good"
            
        elif average >= 1.81:
            return "acceptable"
            
        elif average >= 1.0:
            return "weak"
        
        else:
            return "weak" 
   

    def save(self, *args, **kwargs):  
        manager_avg = self._calculate_manager_average()
        if manager_avg is not None:
            self.manager_average_score = manager_avg
            
        final_combined_avg = self._calculate_combined_average()
        if final_combined_avg is not None:
            final_rating_key = self._get_overall_rating_key(final_combined_avg)
            self.overall_performance = final_rating_key
        else:
            self.overall_performance = None 
        
        super().save(*args, **kwargs)

    class Meta:
          verbose_name = "تقييم العاملين فترة الطوارئ"
          verbose_name_plural = "تقييمات العاملين فترة الطوارئ"
          
    def __str__(self):
        return f"استبيان من {self.employee_name}"
    
CHOICES_LIKERT = [
    (1, 'أوافق بشدة'),
    (2, 'أوافق'),
    (3, 'محايد'),
    (4, 'لا أوافق'),
    (5, 'لا أوافق بشدة'),
]

CHOICES_POSITION = [
    ('تنفيذ', 'موظف تنفيذ'),
    ('مشرف', 'مشرف وحدة'),
    ('رئيس_قسم', 'رئيس قسم / مدير الولاية'),
    ('آخر', 'آخر (يرجى التحديد)'),
]

CHOICES_WORK_DURATION = [
    ('Less_than_year', 'أقل من سنة'),
    ('1_3', 'من 1 إلى 3 سنوات'),
    ('3_5', 'من 3 إلى 5 سنوات'),
    ('more_than_5', 'أكثر من 5 سنوات'),
]


CHOICES_WILAYA = [
    ('Blue_Nile',  'النيل الازرق'),
    ('Kassala',  'كسلا'),
    ('Red_Sea',  'البحر الاحمر'),

hr_employee_survey/templates/hr_survey/employee_sim_list.html
{% extends 'survey/base_survey.html' %}

{% block content %}

{% load i18n %}

<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">

<style>
 
    body {
        background-color: #e9eff4;
        font-family: 'Cairo', sans-serif;
        direction: rtl;
        text-align: right;
    }

    .list-container {
        max-width: 1000px; 
        margin: 30px auto;
        padding: 20px;
        background-color: #ffffff;
        border: 1px solid #ddd;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);
    }

    h2 {
        background-color: #007bff;
        color: white;
        padding: 15px 20px;
        border-radius: 8px;
        margin-bottom: 25px;
        font-size: 1.6rem;
        font-weight: 700;
        text-align: center;
    }
    
    .alert-info {
        padding: 15px;
        margin-bottom: 20px;
        border: 1px solid #007bff;
        color: #004085;
        background-color: #cce5ff;
        border-radius: 5px;
        text-align: center;
        font-weight: bold;
    }

   
    .data-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        table-layout: fixed; 
    }

    .data-table th, .data-table td {
        border: 1px solid #dee2e6;
        padding: 12px;
        text-align: right;
        vertical-align: middle;
        word-wrap: break-word;
    }

    .data-table th {
        background-color: #f1f1f1;
        color: #333;
        font-weight: 700;
        font-size: 0.95rem;
    }

    .data-table tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    .data-table tr:hover {
        background-color: #e2f3ff;
    }

   
    .action-button {
        display: inline-block;
        padding: 8px 15px;
        background-color: #28a745; 
        color: white;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s;
        font-size: 0.9rem;
        text-align: center;
    }

    .action-button:hover {
        background-color: #218838;
    }

   
    @media (max-width: 768px) {
        .list-container {
            margin: 10px;
            padding: 10px;
            overflow-x: auto; 
        }

        .data-table {
            min-width: 700px; 
            table-layout: auto;
        }

        .data-table th, .data-table td {
            padding: 8px;
            font-size: 0.85rem;
        }
        
        .action-button {
            padding: 6px 10px;
            font-size: 0.8rem;
        }

        button {
        background-color: #28a745;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1.1em;
        margin-top: 20px;
        width: 100%;
        transition: background-color 0.3s;
    }

    }
</style>


<div class="list-container">
    <h2> قائمة البيانات المُرسلة </h2>
    <button class="action-button"> <a href="{% url 'surveys:employee_sim_add' %}">  اضافة بيانات شريحة الاتصال </a></li> </button>
    {% if user_data %}
        <table class="data-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th> رقم الهاتف</th>
                    <th>اسم الموظف</th>
                    <th>الادارة</th>

                </tr>
            </thead>
            <tbody>
                {% for data in user_data %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ data.sim_number }}</td>
                        <td>{{ data.name }}</td>
                        <td>{{ data.department }}</td>
                        
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert-info">
            عفواً، لم تقم بإرسال أي بيانات حتى الآن.
        </div>
    {% endif %}

</div>



{% endblock %}

hr_employee_survey/templates/hr_survey/form.html
{% extends 'survey/base_survey.html' %}

{% block content %}

{% load static  %}

{% load i18n %}


<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
<div class="evaluation-form-container">
    <form method="post">
        {% csrf_token %}

        <h2> البيانات الأساسية </h2>
        <div class="form-section">
            
            <div class="form-group">
                <label for="department_display">اسم الموظف </label>  
                {{ form.employee_name }}
                {% if form.employee_name.errors %}
                    <div class="error-message" style="color: red; font-weight: bold;">
                        {{ form.employee_name.errors }}
                    </div>
                {% endif %}
            </div>

            {{ form.employee_code }} 
            <div class="form-group">
               <label for="department_display">كود الموظف</label>  <input type="text" id="employee_code_display" >
            </div>
                        
            <div class="form-group">
               <label for="department_display">البريد الالكتروني  </label>  {{ form.email }} 
            </div>
            
            {{ form.job_title }}
            <div class="form-group">
                <label for="job_title_display">المسمى الوظيفي </label>
                <input type="text" id="job_title_display" >
            </div>
                         
            <div class="form-group">
                <label for="department_display">المدير المباشر</label>  
                <input type="text" value="{{ manager_name|default:request.user.get_full_name }}" >
            </div>

            <div class="form-group">
            <label>فترة التقييم:</label>
            <div class="date-inputs">
                <span>من:</span> 
                {{ form.period_from }} 
                {% if form.period_from.errors %}
                    <div class="error-message">{{ form.period_from.errors }}</div>
                {% endif %}
                
                <span>— إلى:</span> 
                {{ form.period_to }}
                {% if form.period_to.errors %}
                    </br>
                    <div class="error-message">{{ form.period_to.errors }}</div>
                {% endif %}
            </div>
            
            {% if form.non_field_errors %}
                </br>
                <div class="error-message non-field-error">{{ form.non_field_errors }}</div>
            {% endif %}
            
        </div>
        </div>

        <hr>
        <h2>ثانياً: تقييم السلوك الوظيفي </h2>
        <div class="form-section">
            <div class="form-group">
                <label for="department_display">الالتزام بالحضور والانضباط</label>: {{ form.attendance_discipline }}
            </div>
            <div class="form-group">
                <label for="department_display">احترام التعليمات</label>: {{ form.follow_instructions }}
            </div>
            <div class="form-group">
                <label for="department_display">تحمل المسؤولية وتعدد المهام</label>: {{ form.task_responsibility }}
            </div>
            <div class="form-group">
                <label for="department_display">التعاون والعمل ضمن فريق</label>: {{ form.teamwork }}
            </div>
            <div class="form-group">
                <label for="department_display">التواصل الفعال</label>: {{ form.communication }}
            </div>
        </div>

        <hr>

        <h2>ثانياً: تقييم الأداء الفني والمهني</h2>
        <div class="form-section">
            <div class="form-group">
                <label for="department_display">انجاز المهام الرئيسية بجودة وكفاءة</label>: {{ form.main_tasks_quality }}
            </div>
            <div class="form-group">
                <label for="department_display">إنجاز المهام الاضافية خارج التوصيف   </label>  {{ form.extra_tasks }}
            </div>
            <div class="form-group">
                <label for="department_display">القدرة علي التكيف مع ضغط العمل  </label> {{ form.work_pressure }}
            </div>
            <div class="form-group">
                <label for="department_display">الالتزام بالاجراءات والسياسات</label>  {{ form.policies_commitment }}
            </div>
            <div class="form-group">
                <label for="department_display">الابداع في تقديم الحلول</label>  {{ form.creativity }}
            </div>
        </div>

        <hr>

        <h2>ثالثاً  الأداء العام قياس النتائج</h2>
        <div class="form-section">   
            <div class="form-group">
                <label for="department_display">مدي الاستجابة لطبيعة العمل في الطوارئ</label>  {{ form.emergency_response }}
            </div>
            <div class="form-group">
                <label for="department_display">نسبة  تغطية الفجوة عن نقص الكوادر</label>  {{ form.coverage_percentage }}
            </div>
        </div>

        <hr>

        <h2>التوصيات وملخص الأداء </h2>
        <div class="form-section">
            <h3>نقاط القوة لدى الموظف </h3>
            {{ form.strengths }}  
            
            <h3>التحديات </h3>
            {{ form.challenges }}
            
            <h3>الاحتياجات التدريبية </h3>
            {{ form.training_needs }}
            
            <h3>ملاحظات المسؤول المباشر </h3>
            {{ form.manager_notes }}
        </div>
    
        <button type="submit">حفظ التقييم </button>
    </form>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        const employeesData = JSON.parse('{{ employees_json|escapejs }}');

        function updateEmployeeDetails(selectedName) {
            const employee = employeesData.find(emp => emp.name === selectedName);

            if (employee) {
                $('#employee_code_hidden').val(employee.code );
                $('#job_title_hidden').val(employee.job);
                $('#id_email').val(employee.email);
                $('#employee_code_display').val(employee.code);
                $('#job_title_display').val(employee.job);

            } else {
                $('#employee_code_hidden,#direct_manager_email_hidden, #job_title_hidden').val('');
                $('#employee_code_display, #job_title_display').val('');
            }
        }

        $('#employee_name_select').on('change', function() {
            const selectedName = $(this).val();
            updateEmployeeDetails(selectedName);
        });
        
        updateEmployeeDetails($('#employee_name_select').val()); 
    });
</script>


{% endblock %}

hr_employee_survey/templates/hr_survey/survey_list.html
{% extends 'survey/base_survey.html' %}

{% block content %}

{% load i18n %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>قائمة الاستبيانات</title>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"> 
    <style>
        body {
            background-color: #e9eff4;
            font-family: 'Cairo', sans-serif;
        }
        .list-container {
            max-width: 95%;
            margin: 40px auto;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 12px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
        }
        h1 {
            color: #007bff;
            font-weight: 700;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        .table-striped > tbody > tr:nth-of-type(odd) {
            background-color: #f8faff; 
        }
        .table thead th {
            background-color: #007bff; 
            color: white;
            font-weight: 700;
            vertical-align: middle;
        }
        .action-link {
            color: #28a745;
            font-weight: 600;
            text-decoration: none;
        }
        .action-link:hover {
            color: #218838;
            text-decoration: underline;
        }
        .action-button {
        background-color: #28a745;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1.1em;
        margin-top: 20px;
        
    }
    </style>
</head>
<body>
    <div class="container list-container">
        <h1 class="text-center">قائمة استجابات الاستبيان (فاعلية الهيكل التنظيمي)</h1>
            <button class="action-button"> <a href="{% url 'surveys:survey_form' %}">انشاء تقييم جديد </a></li> </button>
        {% if surveys %}
        <div class="table-responsive">
            <table class="table table-striped table-hover align-middle">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">الولاية</th>
                        <th scope="col">المسمى الوظيفي</th> 
                        <th scope="col">التقييم</th>   
                    </tr>
                </thead>
                <tbody>
                    {% for survey in surveys %}
                    <tr>
                        <th scope="row">{{ survey.id }}</th>
                        <td>{{ survey.get_wilaya_display }}</td>
                        <td>{{ survey.position|default:"غير محدد" }}</td> 
                        <td>{{survey.overall_evaluation}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        {% else %}
        <div class="alert alert-warning text-center" role="alert">
            <h4 class="alert-heading">لا توجد استجابات مدخلة بعد!</h4>
            <p>يرجى الانتظار حتى يتم إرسال أول استبيان لعرض البيانات هنا.</p>
        </div>
        {% endif %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}