e_service/urls.py
from django.urls import path,include,reverse
from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.conf import settings
# from django.conf.urls.static import static

# from django.shortcuts import redirect

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# def redirect_to_home(request):
#     return redirect(reverse('admin:index'))

@login_required
def dashboard(request):
    return render(request, 'acceptance/dashboard.html')

urlpatterns = [
    path('managers/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('accounts.urls')), 
    # path('check/', include('check_cordinates.urls')), 
    # path("about/", flatpages_views.flatpage, {"url": "/about/"}, name="about"),
    # path('pa/', include('pa.urls')), 
    path('hr/', include('hr.urls')), 
    path('it/', include('it.urls')), 
    path('fleet/', include('fleet.urls')), 
    path('sandog/', include('sandog.urls')), 
    path('needs/', include('needs_request.urls')),
    
    # path('help/', include('help_request.urls')), 
    path('', include('hr_bot.urls')), 
    path('', dashboard, name='acceptance_home'),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('surveys/', include('hr_employee_survey.urls')),
    path(r'treewidget/', include('treewidget.urls'))
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns = [path('app/', include(urlpatterns))]

#     from django.urls import reverse
#     from django.shortcuts import redirect
#     def redirect_to_home(request):
#         return redirect(reverse('profile:home'))
    
#     urlpatterns.append(
#         path('', redirect_to_home)
#     )

hr/urls.py
from django.urls import path

from django.conf import settings

from .views import Badalat, CheckPayroll, FargKhosomat,Khosomat, KhosomatPlusMokaf2, M2moria, MajlisEl2daraMokaf2View, Mobashara, Modir3amBadalatView, Modir3amKhosomatView, Modir3amMokaf2View, Mokaf2,FargBadalat, Mokaf2MajlisWzara, Ta3agodMosimiMokaf2, Ta3agodMosimiMoratab, Tasoia, Wi7datMosa3idaMokaf2tFarigMoratab,Wi7datMosa3idaMokaf2t

app_name = "hr"
urlpatterns = [                                                        
    path('payroll/badalat', Badalat.as_view(), name='payroll_badalat'),
    path('payroll/khosomat', Khosomat.as_view(), name='payroll_khosomat'),
    path('payroll/check_payroll', CheckPayroll.as_view(), name='payroll_check'),
    path('payroll/mobashara', Mobashara.as_view(), name='payroll_mobashara'),
    path('payroll/mokaf2', Mokaf2.as_view(), name='payroll_mokaf2'),
    path('payroll/mokaf2_majlis', Mokaf2MajlisWzara.as_view(), name='payroll_mokaf2_majlis'),
    path('payroll/moratab_mokaf2', KhosomatPlusMokaf2.as_view(), name='payroll_moratab_mokaf2'),
    path('payroll/m2moria', M2moria.as_view(), name='payroll_m2moria'),

    path('payroll/diff_badalat', FargBadalat.as_view(), name='payroll_diff_badalat'),
    path('payroll/diff_khosomat', FargKhosomat.as_view(), name='payroll_diff_khosomat'),

    path('payroll/wi7dat_mosa3ida_farg_moratab', Wi7datMosa3idaMokaf2tFarigMoratab.as_view(), name='payroll_wi7dat_mosa3ida_farg_moratab'),
    path('payroll/wi7dat_mosa3ida_mokaf2', Wi7datMosa3idaMokaf2t.as_view(), name='payroll_wi7dat_mosa3ida_mokaf2'),

    path('payroll/ta3agod_mosimi_moratab', Ta3agodMosimiMoratab.as_view(), name='payroll_ta3agod_mosimi_moratab'),
    path('payroll/ta3agod_mosimi_mokaf2', Ta3agodMosimiMokaf2.as_view(), name='payroll_ta3agod_mosimi_mokaf2'),

    path('payroll/majlis_el2dara_mokaf2', MajlisEl2daraMokaf2View.as_view(), name='payroll_majlis_el2dara_mokaf2'),

    path('payroll/modir_3am_badalat', Modir3amBadalatView.as_view(), name='payroll_modir_3am_badalat'),
    path('payroll/modir_3am_khosomat', Modir3amKhosomatView.as_view(), name='payroll_modir_3am_khosomat'),
    path('payroll/modir_3am_mokaf2', Modir3amMokaf2View.as_view(), name='payroll_modir_3am_mokaf2'),
    path('payroll/tasoia', Tasoia.as_view(), name='payroll_tasoia'),

]

pa/urls.py
from django.urls import path
from django.conf.urls.static import static

from django.conf import settings

from pa.views.commitment import TblCompanyCommitmentDeleteView, TblCompanyCommitmentUpdateView
from pa.views.commitment_schedular import TblCompanyCommitmentScheduleCreateView, TblCompanyCommitmentScheduleDeleteView, TblCompanyCommitmentScheduleListView, TblCompanyCommitmentScheduleReadonlyView, TblCompanyCommitmentScheduleUpdateView
from pa.views.daily import PaDailyView
from pa.views.payment import TblCompanyPaymentDeleteView, TblCompanyPaymentUpdateView
from pa.views.payment_status import PaymentStatusView
from pa.views.request import TblCompanyRequestDeleteView, TblCompanyRequestUpdateView
from pa.views.request_status import RequestStatusView

from .views import LkpLicenseSelectView, TblCompanyOpenningBalanceListView,TblCompanyOpenningBalanceCreateView,TblCompanyOpenningBalanceReadonlyView,TblCompanyOpenningBalanceUpdateView,TblCompanyOpenningBalanceDeleteView, \
                   TblCompanyCommitmentListView,TblCompanyCommitmentCreateView,TblCompanyCommitmentReadonlyView, \
                   TblCompanyRequestListView,TblCompanyRequestCreateView,TblCompanyRequestReadonlyView, \
                   TblCompanyPaymentListView,TblCompanyPaymentCreateView,TblCompanyPaymentReadonlyView


app_name = "pa"
urlpatterns = [                                                        
    path('', PaymentStatusView.as_view(), name='home'),

    path('lkp_license/<int:master_id>/<int:dependent_id>/', LkpLicenseSelectView.as_view(), name='lkp_license_select'),

    path('openning_balance/', TblCompanyOpenningBalanceListView.as_view(), name='openning_balance_list'),
    path('openning_balance/<int:type>/', TblCompanyOpenningBalanceListView.as_view(), name='openning_balance_list'),
    path('openning_balance/<int:pk>/edit/', TblCompanyOpenningBalanceUpdateView.as_view(), name='openning_balance_edit'),    
    path('openning_balance/<int:pk>/show/', TblCompanyOpenningBalanceReadonlyView.as_view(), name='openning_balance_show'),    
    path('openning_balance/<int:pk>/delete/', TblCompanyOpenningBalanceDeleteView.as_view(), name='openning_balance_delete'),    
    path('openning_balance/add/', TblCompanyOpenningBalanceCreateView.as_view(), name='openning_balance_add'),

    path('commitment/', TblCompanyCommitmentListView.as_view(), name='commitment_list'),
    path('commitment/<int:type>/', TblCompanyCommitmentListView.as_view(), name='commitment_list'),
    path('commitment/<int:pk>/edit/', TblCompanyCommitmentUpdateView.as_view(), name='commitment_edit'),    
    path('commitment/<int:pk>/show/', TblCompanyCommitmentReadonlyView.as_view(), name='commitment_show'),    
    path('commitment/<int:pk>/delete/', TblCompanyCommitmentDeleteView.as_view(), name='commitment_delete'),    
    path('commitment/add/', TblCompanyCommitmentCreateView.as_view(), name='commitment_add'),

    path('commitment_schedule/', TblCompanyCommitmentScheduleListView.as_view(), name='commitment_schedule_list'),
    path('commitment_schedule/<int:type>/', TblCompanyCommitmentScheduleListView.as_view(), name='commitment_schedule_list'),
    path('commitment_schedule/<int:pk>/edit/', TblCompanyCommitmentScheduleUpdateView.as_view(), name='commitment_schedule_edit'),    
    path('commitment_schedule/<int:pk>/show/', TblCompanyCommitmentScheduleReadonlyView.as_view(), name='commitment_schedule_show'),    
    path('commitment_schedule/<int:pk>/delete/', TblCompanyCommitmentScheduleDeleteView.as_view(), name='commitment_schedule_delete'),    
    path('commitment_schedule/add/', TblCompanyCommitmentScheduleCreateView.as_view(), name='commitment_schedule_add'),

    path('request/', TblCompanyRequestListView.as_view(), name='request_list'),
    path('request/<int:type>/', TblCompanyRequestListView.as_view(), name='request_list'),
    path('request/<int:pk>/edit/', TblCompanyRequestUpdateView.as_view(), name='request_edit'),    
    path('request/<int:pk>/show/', TblCompanyRequestReadonlyView.as_view(), name='request_show'),    
    path('request/<int:pk>/delete/', TblCompanyRequestDeleteView.as_view(), name='request_delete'),    
    path('request/add/', TblCompanyRequestCreateView.as_view(), name='request_add'),

    path('payment/', TblCompanyPaymentListView.as_view(), name='payment_list'),
    path('payment/<int:type>/', TblCompanyPaymentListView.as_view(), name='payment_list'),
    path('payment/<int:pk>/edit/', TblCompanyPaymentUpdateView.as_view(), name='payment_edit'),    
    path('payment/<int:pk>/show/', TblCompanyPaymentReadonlyView.as_view(), name='payment_show'),    
    path('payment/<int:pk>/delete/', TblCompanyPaymentDeleteView.as_view(), name='payment_delete'),    
    path('payment/add/', TblCompanyPaymentCreateView.as_view(), name='payment_add'),

    path('daily/', PaDailyView.as_view(), name='daily_list'),
    path('request_status/', RequestStatusView.as_view(), name='request_status'),
    path('payment_status/', PaymentStatusView.as_view(), name='payment_status'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pa/views/commitment.py
from django.shortcuts import get_object_or_404,render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _

from django.contrib import messages

from company_profile.models import TblCompanyProduction
from pa.forms.commitment import TblCompanyAddCommitmentForm, TblCompanyCommitmentDetailForm, TblCompanyRequestChooseCompanyForm, TblCompanyShowEditCommitmentForm
from pa.utils import get_company_types_from_groups

from ..models import STATE_TYPE_CONFIRM, TblCompanyCommitmentDetail, TblCompanyCommitmentMaster

from ..tables import TblCompanyCommitmentTable,CommitmentFilter

from .application import ApplicationDeleteMasterDetailView, ApplicationDeleteView, ApplicationListView, ApplicationCreateView, ApplicationMasterDetailCreateView, ApplicationMasterDetailUpdateView, ApplicationReadonlyView, ApplicationUpdateView
from .utils import get_company_details

model_master = TblCompanyCommitmentMaster
details = [
        {
            "id":1,
            "title":"تفاصيل السجل",
            "args":[
                model_master,
                TblCompanyCommitmentDetail
            ],
            "kwargs":{
            #    "fields":['item','amount_factor'],
               "form": TblCompanyCommitmentDetailForm,
                "extra":0,
                "min_num":1, 
                "validate_min":True,
                "can_delete":True,
            },
        },
    ]


class TblCompanyCommitmentListView(ApplicationListView):
    model = model_master
    table_class = TblCompanyCommitmentTable
    filterset_class = CommitmentFilter
    menu_name = "pa:commitment_list"
    title = _("List of commitments")
    
    def get_queryset(self):                
        query = super().get_queryset()
        query = query.filter(company__company_type__in=get_company_types_from_groups(self.request.user))
        return query

class TblCompanyCommitmentCreateView(ApplicationMasterDetailCreateView):
    model = model_master
    form_class = TblCompanyAddCommitmentForm
    details = details
    menu_name = "pa:commitment_list"
    title = _("Add new commitment")            

    def get(self,request, *args, **kwargs):   
        company_id = request.GET.get('company')
        if not company_id:
            self.extra_context['form'] = TblCompanyRequestChooseCompanyForm
            self.extra_context['form'].user = request.user
            self.extra_context['details'] = []
            return render(request, 'pa/application_choose.html', self.extra_context)
        
        obj = get_object_or_404(TblCompanyProduction,id=company_id)
        form = self.form_class(company_id=obj.id,initial={
            "company": obj,
        })

        self.extra_context['form'] = form

        for detail in self.details_formset:
            if detail.get('id') == 1:
                TblCompanyCommitmentDetailFormWithCompanyType=TblCompanyCommitmentDetailForm
                TblCompanyCommitmentDetailFormWithCompanyType.company_type = obj.company_type
                detail['formset'].form = TblCompanyCommitmentDetailFormWithCompanyType
        return render(request, self.template_name, self.extra_context)
    
    def post(self,request,*args, **kwargs):        
        company_id = request.POST.get('company')

        form = self.form_class(request.POST,request.FILES,company_id=company_id)

        self.extra_context['form'] = form
        return super().post(request,*args, **kwargs)

class TblCompanyCommitmentUpdateView(ApplicationMasterDetailUpdateView):
    model = model_master
    form_class = TblCompanyShowEditCommitmentForm
    details = details
    menu_name = "pa:commitment_list"
    menu_show_name = "pa:commitment_show"
    title = _("Edit commitment")

    def get(self,request,*args, **kwargs):        
        obj = self.get_object()
        self.extra_context['company'] = get_company_details(obj)

        for detail in self.details_formset:
            if detail.get('id') == 1:
                TblCompanyCommitmentDetailFormWithCompanyType=TblCompanyCommitmentDetailForm
                TblCompanyCommitmentDetailFormWithCompanyType.company_type = obj.company.company_type
                detail['formset'].form = TblCompanyCommitmentDetailFormWithCompanyType

        return super().get(request,*args, **kwargs)

class TblCompanyCommitmentReadonlyView(ApplicationReadonlyView):
    model = model_master
    form_class = TblCompanyShowEditCommitmentForm
    details = details
    menu_name = "pa:commitment_list"
    menu_edit_name = "pa:commitment_edit"
    menu_delete_name = "pa:commitment_delete"
    title = _("Show added commitment")

    def get(self,request,*args, **kwargs):        
        obj = self.get_object()
        self.extra_context['company'] = get_company_details(obj)

        for detail in self.details_formset:
            if detail.get('id') == 1:
                TblCompanyCommitmentDetailFormWithCompanyType=TblCompanyCommitmentDetailForm
                TblCompanyCommitmentDetailFormWithCompanyType.company_type = obj.company.company_type
                detail['formset'].form = TblCompanyCommitmentDetailFormWithCompanyType

        return super().get(request,*args, **kwargs)

class TblCompanyCommitmentDeleteView(ApplicationDeleteMasterDetailView):
    model = model_master
    form_class = TblCompanyShowEditCommitmentForm
    details = details
    menu_name = "pa:commitment_list"
    title = _("Delete commitment")

    def get(self,request,*args, **kwargs):        
        obj = self.get_object()
        self.extra_context['company'] = get_company_details(obj)
        return super().get(request,*args, **kwargs)

pa/views/request_status.py
from django.shortcuts import render
from django.views.generic import View
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.db.models import FloatField, CharField, Value,Sum,F
from django.contrib.auth.mixins import LoginRequiredMixin

from .application import TranslationMixin, UserPermissionMixin
from ..forms import PaDailyForm
from ..models import TblCompanyOpenningBalanceDetail, TblCompanyOpenningBalanceMaster, TblCompanyPaymentDetail, TblCompanyRequestDetail, TblCompanyRequestMaster,TblCompanyPaymentMaster,STATE_TYPE_CONFIRM

class RequestStatusView(LoginRequiredMixin,UserPermissionMixin,TranslationMixin,View):
    form = PaDailyForm
    menu_name = "pa:request_status"
    title = "مديونية الشركات"
    template_name = "pa/request_status.html"     
    user_groups = ['pa_data_entry','pa_manager']

    def dispatch(self, *args, **kwargs):         
        self.extra_context = {
                            "menu_name":self.menu_name,
                            "title":self.title,
                            "table":None,
         }
        return super().dispatch(*args, **kwargs)       
        
    def get(self, request, *args, **kwargs):
        form = self.form(request.GET)
        qs = None

        self.extra_context["form"] = self.form
        self.extra_context["qs"] = qs
        self.extra_context["is_get"] = True
        
        return render(request, self.template_name, self.extra_context)
    
    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        qs = None
        request_total = 0
        payment_total = 0

        if form.is_valid():
            company = form.cleaned_data["company"]
            currency = form.cleaned_data["currency"]
            from_dt = form.cleaned_data["from_dt"]
            to_dt = form.cleaned_data["to_dt"]
            qs = TblCompanyRequestMaster.objects.filter(
                from_dt__gte=from_dt,
                to_dt__lte=to_dt,
                currency=currency,
                state=STATE_TYPE_CONFIRM,
            )

            if company:
                qs = qs.filter(
                    commitment__company=company,
                )

            # print(qs)
            sum_request = 0
            sum_payment = 0
            sum_remain = 0

            for req in qs:
                sum_request += req.total or 0
                sum_payment += req.sum_of_confirmed_payment or 0
                sum_remain += req.remain_payment or 0

            self.extra_context["qs"] = qs
            self.extra_context["sum_request"] = sum_request
            self.extra_context["sum_payment"] = sum_payment
            self.extra_context["sum_remain"] = sum_remain

        self.extra_context["form"] = form
        return render(request, self.template_name, self.extra_context)

pa/templates/pa/application_add.html
{% extends 'pa/base.html' %}
{% load static  %}

{% load i18n %}
{% load bootstrap3 %}
{% load auth_extras %}

{% block content %}
<h1 class="page-header">{{title}}</h1>
{% bootstrap_messages %}

<form  method="post" enctype="multipart/form-data" onsubmit="this.querySelector('button').disabled = true;">
{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="{% translate "Save Draft" %}" name="_save_draft" class="btn btn-primary">
    {% if request.user|has_group:"pa_manager" %}
    <input type="submit" value="{% translate "Save & Confirm" %}" name="_save_confirm" class="btn btn-default">
    {% endif %}
    {% endbuttons %}
</form>
<script type="text/javascript" src="{% static 'company_profile/js/admin_jsi18n.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
{{ form.media }}

{% endblock content %}

pa/templates/pa/application_choose.html
{% extends 'pa/base.html' %}
{% load static  %}

{% load i18n %}
{% load bootstrap3 %}
{% load auth_extras %}

{% block content %}
<h1 class="page-header">{{title}}</h1>
{% bootstrap_messages %}

<form  method="get" enctype="multipart/form-data">
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="{% translate "Choose" %}" name="_choose_btn" class="btn btn-primary">
    {% endbuttons %}
</form>
<script type="text/javascript" src="{% static 'company_profile/js/admin_jsi18n.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
{{ form.media }}

{% endblock content %}

pa/templates/pa/application_delete.html
{% extends 'pa/base.html' %}
{% load static  %}

{% load i18n %}
{% load bootstrap3 %}

{% block content %}
<h1 class="page-header">{{title}}</h1>
{% bootstrap_messages %}

<form  method="post" enctype="multipart/form-data">
{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="{% translate "Delete Draft" %}" name="_delete_draft" class="btn btn-primary">
    {% endbuttons %}
</form>
<script type="text/javascript" src="{% static 'company_profile/js/admin_jsi18n.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
{{ form.media }}

{% endblock content %}

pa/templates/pa/application_list.html
{% extends 'pa/base.html' %}
{% load i18n %}

{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% load auth_extras %}

{% block content %}
<h1 class="page-header">{{title}}</h1>
{% bootstrap_messages %}

{% if filter %}
<form action="" method="get" class="form form-inline filter">
	{% bootstrap_form filter.form  %}
	<input type="submit" value="{% translate "Search" %}" class="btn btn-default" role="button">
</form>
{% load static  %}

<script type="text/javascript" src="{% static 'company_profile/js/admin_jsi18n.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>

<div class="screen_only">
	<br/>
	{% endif %}

	<a class="btn btn-primary" href="{% url menu_name%}add/" role="button">
		<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
		{% translate "New record" %}
	</a>
	<br/>
</div>
<br/>

	{% comment %} <nav>
	  <ul class="nav nav-tabs">
		<li role="presentation" class="{% if type == 1 %}active{% endif %}"><a href="{% url menu_name type=1 %}" >{% translate "In progress" %}</a></li>
		<li role="presentation" class=" {% if type == 2 %}active{% endif %}"><a href="{% url menu_name  type=2%}" >{% translate "Approved" %}</a></li>
		<li role="presentation" class=" {% if type == 3 %}active{% endif %}"><a href="{% url menu_name  type=3 %}">{% translate "Rejected" %}</a></li>
	  </ul>
	</nav>
	<br/> {% endcomment %}
	<div  class="panel panel-default">
		{% render_table table %}
	</div>

{% endblock content %}


pa/templates/pa/pa_daily.html
{% extends 'pa/base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load static  %}
{% load l10n %}
{% load humanize %}

{% block title %}
	{{title}}
{% endblock %}

{% block content %}
{% localize off %}
<h1 class="page-header">{{title}}</h1>
{% bootstrap_messages %}

<form action="" method="post" class="screen_only" novalidate>
	{% csrf_token %}
	<div class="row">
		<div class="col-md-6">
    		{% bootstrap_field form.company %}
		</div>
		<div class="col-md-6">
    		{% bootstrap_field form.currency %}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			{% bootstrap_field form.from_dt %}
		</div>
		<div class="col-md-6">
			{% bootstrap_field form.to_dt %}
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			{% buttons %}
			<input type="submit" value="{% translate "Search" %}" class="btn btn-primary center-block" role="button">
			{% endbuttons %}
		</div>
	</div>
</form>

<div class="print_only">
	<div class="filter">
		<label>{%translate "company"%}:</label> {% if form.company.value%} {{form.company.display}} {%else%} {{"الكل"}} {%endif%}
		<label>{%translate "currency"%}:</label> {% translate form.currency.value%}
	</div>
	<div class="filter">
		<label>{%translate "from_dt"%}:</label> {{form.cleaned_data.from_dt|date:"Y/m/d"}}
		<label>{%translate "to_dt"%}:</label> {{form.cleaned_data.to_dt|date:"Y/m/d"}}
	</div>
</div>

<script type="text/javascript" src="{% static 'company_profile/js/admin_jsi18n.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
{{ form.media }}

{%if form.is_valid %}

	<div class="screen_only">
		<br/>
		<a class="btn btn-default"  onClick="window.print()" href="#" role="button">
			<span class="glyphicon glyphicon-print" aria-hidden="true"></span>
			{% translate "Print" %}
		</a>
		<br/>
	</div>
	<br/>

	<div  class="panel panel-default">
		<table class="table">
			<thead>
				<tr>
					<th>{%translate "date"%}</th>
					<th>{%translate "financial item"%}</th>
					<th>{%translate "currency"%}</th>
					<th>{%translate "exchange_rate"%}</th>
					<th>{%translate "credit"%}</th>
					<th>{%translate "debit"%}</th>
					<th>{%translate "balance"%}</th>
					{% comment %} <th>{%translate "company"%}</th> {% endcomment %}
					{% comment %} <th>{%translate "type"%}</th> {% endcomment %}
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>&nbsp;</th>
					<th>{%translate "opening_balance"%}</th>
					<th>{%translate request.POST.currency%}</th>
					<th>1.0</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>{{opening|unlocalize|intcomma}}</th>
					{% comment %} <th>{%translate "company"%}</th> {% endcomment %}
					{% comment %} <th>opening</th> {% endcomment %}
				</tr>
				<tr>
					<th>{%translate "before"%} ({{from_dt|date:"d-m-Y"}})</th>
					<th>{%translate "befor_balance"%}</th>
					<th>{%translate request.POST.currency%}</th>
					<th>1.0</th>
					<th>{{payment_opening|unlocalize|intcomma}}</th>
					<th>{{request_opening|unlocalize|intcomma}}</th>
					<th>{{balance_opening|unlocalize|intcomma}}</th>
					{% comment %} <th>{%translate "company"%}</th> {% endcomment %}
					{% comment %} <th>opening</th> {% endcomment %}
				</tr>
				{%for m in data %}
				<tr>
					<td>{{m.1|date:"Y-m-d"}}</td>
					{%if m.6 == 'request'%}
						<td><a href="{% url 'pa:request_show' m.0 %}">{{m.2}}</a></td>
					{% elif m.6 == 'payment' %}
						<td><a href="{% url 'pa:payment_show' m.0 %}">{{m.2}}</a></td>
					{% endif %}
					<td>{% translate m.4%}</td>
					<td>{{m.5}}</td>
					<td>
						{%if m.6 == 'request'%}
						&nbsp;
						{% else %}
						{{m.3|unlocalize|intcomma}}
						&nbsp;
						{% endif %}
					</td>
					<td>
						{%if m.6 == 'payment'%}
						&nbsp;
						{% else %}
						{{m.3|unlocalize|intcomma}}
						{% endif %}
					</td>
					<th>{{m.7|unlocalize|intcomma}}</th>
					{% comment %} <th>{{m.8}}</th> {% endcomment %}
					{% comment %} <th>{{m.6}}</th> {% endcomment %}
				</tr>
				{%endfor%}
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>{{payment_total|unlocalize|intcomma}}</th>
					<th>{{request_total|unlocalize|intcomma}}</th>
					<th>{{balance_total|unlocalize|intcomma}}</th>
					<th>&nbsp;</th>
					{% comment %} <th>&nbsp;</th> {% endcomment %}
				</tr>
			</tbody>
		</table>
	</div>
{%endif%}
{% endlocalize %}
{% endblock content %}
