e_service/urls.py
from django.urls import path,include,reverse
from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.conf import settings
# from django.conf.urls.static import static

# from django.shortcuts import redirect

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# def redirect_to_home(request):
#     return redirect(reverse('admin:index'))

@login_required
def dashboard(request):
    return render(request, 'acceptance/dashboard.html')

urlpatterns = [
    path('managers/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('accounts.urls')), 
    # path('check/', include('check_cordinates.urls')), 
    # path("about/", flatpages_views.flatpage, {"url": "/about/"}, name="about"),
    # path('pa/', include('pa.urls')), 
    path('hr/', include('hr.urls')), 
    path('it/', include('it.urls')), 
    path('fleet/', include('fleet.urls')), 
    path('sandog/', include('sandog.urls')), 
    path('needs/', include('needs_request.urls')),
    
    # path('help/', include('help_request.urls')), 
    path('', include('hr_bot.urls')), 
    path('', dashboard, name='acceptance_home'),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('surveys/', include('hr_employee_survey.urls')),
    path(r'treewidget/', include('treewidget.urls'))
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns = [path('app/', include(urlpatterns))]

#     from django.urls import reverse
#     from django.shortcuts import redirect
#     def redirect_to_home(request):
#         return redirect(reverse('profile:home'))
    
#     urlpatterns.append(
#         path('', redirect_to_home)
#     )

gold_travel/urls.py
from django.urls import path

from django.conf import settings

from .views import GoldTravelCert, WhomMayConcern, get_exported_gold


app_name = "gold_travel"
urlpatterns = [                                                        
    path('certificate/gold_travel', GoldTravelCert.as_view(), name='gold_travel_cert'),
    path('certificate/whom_may_concern', WhomMayConcern.as_view(), name='whom_may_concern'),
    path('geojson/exported_gold', get_exported_gold, name='get_exported_gold'),

]

hr/urls.py
from django.urls import path

from django.conf import settings

from .views import Badalat, CheckPayroll, FargKhosomat,Khosomat, KhosomatPlusMokaf2, M2moria, MajlisEl2daraMokaf2View, Mobashara, Modir3amBadalatView, Modir3amKhosomatView, Modir3amMokaf2View, Mokaf2,FargBadalat, Mokaf2MajlisWzara, Ta3agodMosimiMokaf2, Ta3agodMosimiMoratab, Tasoia, Wi7datMosa3idaMokaf2tFarigMoratab,Wi7datMosa3idaMokaf2t

app_name = "hr"
urlpatterns = [                                                        
    path('payroll/badalat', Badalat.as_view(), name='payroll_badalat'),
    path('payroll/khosomat', Khosomat.as_view(), name='payroll_khosomat'),
    path('payroll/check_payroll', CheckPayroll.as_view(), name='payroll_check'),
    path('payroll/mobashara', Mobashara.as_view(), name='payroll_mobashara'),
    path('payroll/mokaf2', Mokaf2.as_view(), name='payroll_mokaf2'),
    path('payroll/mokaf2_majlis', Mokaf2MajlisWzara.as_view(), name='payroll_mokaf2_majlis'),
    path('payroll/moratab_mokaf2', KhosomatPlusMokaf2.as_view(), name='payroll_moratab_mokaf2'),
    path('payroll/m2moria', M2moria.as_view(), name='payroll_m2moria'),

    path('payroll/diff_badalat', FargBadalat.as_view(), name='payroll_diff_badalat'),
    path('payroll/diff_khosomat', FargKhosomat.as_view(), name='payroll_diff_khosomat'),

    path('payroll/wi7dat_mosa3ida_farg_moratab', Wi7datMosa3idaMokaf2tFarigMoratab.as_view(), name='payroll_wi7dat_mosa3ida_farg_moratab'),
    path('payroll/wi7dat_mosa3ida_mokaf2', Wi7datMosa3idaMokaf2t.as_view(), name='payroll_wi7dat_mosa3ida_mokaf2'),

    path('payroll/ta3agod_mosimi_moratab', Ta3agodMosimiMoratab.as_view(), name='payroll_ta3agod_mosimi_moratab'),
    path('payroll/ta3agod_mosimi_mokaf2', Ta3agodMosimiMokaf2.as_view(), name='payroll_ta3agod_mosimi_mokaf2'),

    path('payroll/majlis_el2dara_mokaf2', MajlisEl2daraMokaf2View.as_view(), name='payroll_majlis_el2dara_mokaf2'),

    path('payroll/modir_3am_badalat', Modir3amBadalatView.as_view(), name='payroll_modir_3am_badalat'),
    path('payroll/modir_3am_khosomat', Modir3amKhosomatView.as_view(), name='payroll_modir_3am_khosomat'),
    path('payroll/modir_3am_mokaf2', Modir3amMokaf2View.as_view(), name='payroll_modir_3am_mokaf2'),
    path('payroll/tasoia', Tasoia.as_view(), name='payroll_tasoia'),

]

gold_travel/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from company_profile.models import LkpState

class LoggingModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created_at`` and ``updated_at`` fields for responsable user.
    """
    created_at = models.DateTimeField(_("created_at"),auto_now_add=True,editable=False,)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,related_name="+",editable=False,verbose_name=_("created_by")) 
    
    updated_at = models.DateTimeField(_("updated_at"),auto_now=True,editable=False)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,related_name="+",editable=False,verbose_name=_("updated_by"))
    
    class Meta:
        abstract = True

class LkpStateDetails(models.Model):
    state = models.OneToOneField(LkpState, on_delete=models.PROTECT,related_name="state_gold_travel",verbose_name=_("state"))
    code = models.CharField(_("code"),max_length=4)
    next_serial_no = models.IntegerField(_("export_next_serial_no"))
    reexport_next_serial_no = models.IntegerField(_("reexport_next_serial_no"), default=1)
    silver_next_serial_no = models.IntegerField(_("silver_next_serial_no"), default=1)
    has_2lestikhbarat_2l3askria = models.BooleanField(_("has_2lestikhbarat_2l3askria"))
    
    class Meta:
        verbose_name = _("gold travel state detail")
        verbose_name_plural = _("gold travel state details")

class TblStateRepresentative(models.Model):
    AUTHORITY_SMRC = 2
    AUTHORITY_2MN_2LM3ADIN = 3
    AUTHORITY_SHORTAT_2LM3ADIN = 4
    AUTHORITY_2LESTIKHBARAT_2L3ASKRIA = 5
    AUTHORITY_SMRC_NAFIZA = 6

    AUTHORITY_CHOICES = {
        AUTHORITY_SMRC: _('authority_smrc'),
        AUTHORITY_2MN_2LM3ADIN: _('authority_2mn_2lm3adin'),
        AUTHORITY_SHORTAT_2LM3ADIN: _('authority_shortat_2lm3adin'),
        AUTHORITY_2LESTIKHBARAT_2L3ASKRIA: _('authority_2lestikhbarat_2l3askria'),
        AUTHORITY_SMRC_NAFIZA: _('authority_smrc_nafiza'),
    }

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,related_name="state_representative",verbose_name=_("user"))
    name = models.CharField(_("name"),max_length=100)
    state = models.ForeignKey(LkpState, on_delete=models.PROTECT,verbose_name=_("state"))
    authority = models.IntegerField(_("authority"), choices=AUTHORITY_CHOICES, default=AUTHORITY_SMRC)

    def __str__(self):
        return f'{self.user} ({self.state.name})'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['state', 'authority'], name='unique_state_authority ')
        ]

        verbose_name = _("state representative")
        verbose_name_plural = _("state representatives")

class LkpOwner(models.Model):
    STATE_ACTIVE = 1
    STATE_INACTIVE = 2

    STATE_CHOICES = {
        STATE_ACTIVE: _('active'),
        STATE_INACTIVE: _('inactive'),
    }

    name = models.CharField(_("name"),max_length=100)
    state = models.IntegerField(_("record_state"), choices=STATE_CHOICES, default=STATE_ACTIVE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ["name"]
        verbose_name = _("owner_name")
        verbose_name_plural = _("owner_name")

class AppMoveGold(LoggingModel):
    DESTINATION_SSMO = 1
    DESTINATION_CHOICES = {
        DESTINATION_SSMO: _('ssmo_name'),
    }

    FORM_TYPE_GOLD_EXPORT = 1
    FORM_TYPE_GOLD_REEXPORT = 2
    FORM_TYPE_SILVER_EXPORT = 3
    FORM_TYPE_CHOICES = {
        FORM_TYPE_GOLD_EXPORT: _('form_type_gold_export'),
        FORM_TYPE_GOLD_REEXPORT: _('form_type_gold_reexport'),
        FORM_TYPE_SILVER_EXPORT: _('form_type_silver_export'),
    }

    STATE_DRAFT = 1
    STATE_SMRC = 2
    STATE_2MN_2LM3ADIN = 3
    STATE_SHORTAT_2LM3ADIN = 4
    STATE_2LESTIKHBARAT_2L3ASKRIA = 5
    STATE_SSMO = 6
    STATE_WAIVED = 7
    STATE_CANCELED = 8

    STATE_CHOICES = {
        STATE_DRAFT: _('state_draft'),
        STATE_SMRC: _('state_smrc'),
        STATE_2MN_2LM3ADIN: _('state_2mn_2lm3adin'),
        STATE_SHORTAT_2LM3ADIN: _('state_shortat_2lm3adin'),
        STATE_2LESTIKHBARAT_2L3ASKRIA: _('state_2lestikhbarat_2l3askria'),
        STATE_SSMO: _('state_ssmo'),
        STATE_WAIVED: _('state_waived'),
        STATE_CANCELED: _('state_canceled'),
    }

    IDENTITY_PASSPORT = 1
    IDENTITY_PERSONAL = 2
    IDENTITY_NATIONAL_ID = 3
    IDENTITY_DRIVING_LICENSE = 4

    IDENTITY_CHOICES = {
        IDENTITY_PASSPORT: _('identity_passport'),
        IDENTITY_PERSONAL: _('identity_personal'),
        IDENTITY_NATIONAL_ID: _('identity_national_id'),
        IDENTITY_DRIVING_LICENSE: _('identity_driving_license'),
    }

    def attachement_path(self, filename):
        company = self.owner_name
        date = self.created_at.date()
        return "company_{0}/travel/{1}/{2}".format(company,date, filename)    

    form_type = models.IntegerField(_("form_type"), choices=FORM_TYPE_CHOICES, default=FORM_TYPE_GOLD_EXPORT)
    code = models.CharField(_("code"),max_length=20, default='')
    date = models.DateField(_("date"))
    destination = models.IntegerField(_("destination"), choices=DESTINATION_CHOICES, default=DESTINATION_SSMO)
    # owner_name_str = models.CharField(_("owner_name"),max_length=100,null=True,blank=True)
    owner_name_lst = models.ForeignKey(LkpOwner, on_delete=models.PROTECT,verbose_name=_("owner_name"))
    owner_address = models.CharField(_("owner_address"),max_length=150)
    repr_name = models.CharField(_("repr_name"),max_length=100)
    repr_address = models.CharField(_("repr_address"),max_length=150)
    repr_phone = models.CharField(_("repr_phone"),max_length=30)
    repr_identity_type = models.IntegerField(_("repr_identity_type"), choices=IDENTITY_CHOICES, default=IDENTITY_PASSPORT)
    repr_identity = models.CharField(_("repr_identity"),max_length=50)
    repr_identity_issue_date = models.DateField(_("repr_identity_issue_date"))
    # gold_weight_in_gram = models.FloatField(_("gold_weight_in_gram"))
    # gold_alloy_count = models.IntegerField(_("gold_alloy_count"))
    # gold_description = models.CharField(_("gold_description"),max_length=100)
    state = models.IntegerField(_("record_state"), choices=STATE_CHOICES, default=STATE_DRAFT)
    attachement_file = models.FileField(_("attachement_file"),upload_to=attachement_path,null=True,blank=True)
    source_state = models.ForeignKey(LkpState, on_delete=models.PROTECT,verbose_name=_("state"))

    @property
    def owner_name(self):
        return self.owner_name_lst.name

    @property
    def gold_weight_in_gram(self):
        sum = self.appmovegolddetails_set.aggregate(sum=models.Sum("alloy_weight_in_gram"))['sum'] or 0
        return round(sum,2) #f'{sum:.2f}'

    def gold_alloy_count_per_shape(self,shape=None):
        if(not shape):
            return self.appmovegolddetails_set.count()
        else:
            return self.appmovegolddetails_set.filter(alloy_shape=shape).count()
    @property        
    def gold_alloy_count(self):
        return self.gold_alloy_count_per_shape()
    
    @property
    def gold_description(self):
        arr = []
        for shape,shape_desc in AppMoveGoldDetails.ALLOY_SHAPE_CHOICES.items():
            count = self.gold_alloy_count_per_shape(shape=shape)
            if count > 0:
                arr.append(f"عدد ({count}) سبيكة {shape_desc} الشكل")

        return '، '.join(arr)+'.'

    def __str__(self):
        return f'{self.owner_name} ({self.code})'

    class Meta:
        ordering = ["-date","-id"]
        verbose_name = _("Move Gold")
        verbose_name_plural = _("Move Gold")
        indexes = [
            models.Index(fields=["code"]),
            # models.Index(fields=["owner_name"]),
        ]

class AppMoveGoldExportGoldManager(models.Manager):
    def get_queryset(self):
       return super().get_queryset().filter(form_type=AppMoveGold.FORM_TYPE_GOLD_EXPORT)

class AppMoveGoldExportGold(AppMoveGold):
    objects = AppMoveGoldExportGoldManager()
    default_manager = objects

    class Meta:
        proxy = True
        verbose_name = _("Export Gold")
        verbose_name_plural = _("Export Gold")

class AppMoveGoldREExportGoldManager(models.Manager):
    def get_queryset(self):
       return super().get_queryset().filter(form_type=AppMoveGold.FORM_TYPE_GOLD_REEXPORT)

class AppMoveGoldREExportGold(AppMoveGold):
    objects = AppMoveGoldREExportGoldManager()
    default_manager = objects

    class Meta:
        proxy = True
        verbose_name = _("Re-export Gold")
        verbose_name_plural = _("Re-export Gold")

class AppMoveGoldExportSilverManager(models.Manager):
    def get_queryset(self):
       return super().get_queryset().filter(form_type=AppMoveGold.FORM_TYPE_SILVER_EXPORT)

class AppMoveGoldExportSilver(AppMoveGold):
    objects = AppMoveGoldExportSilverManager()
    default_manager = objects

    class Meta:
        proxy = True
        verbose_name = _("Export Silver")
        verbose_name_plural = _("Export Silver")

class AppMoveGoldDetails(models.Model):
    ALLOY_SHAPE_RECTANGULAR = 1
    ALLOY_SHAPE_CIRCULAR = 2
    ALLOY_SHAPE_CHOICES = {
        ALLOY_SHAPE_RECTANGULAR: _('alloy_shape_rectangular'),
        ALLOY_SHAPE_CIRCULAR: _('alloy_shape_circular'),
    }

    master  = models.ForeignKey(AppMoveGold, on_delete=models.PROTECT)
    alloy_id = models.CharField(_("alloy_id"),max_length=20, default='')
    alloy_weight_in_gram = models.FloatField(_("alloy_weight_in_gram"))
    alloy_shape = models.IntegerField(_("alloy_shape"), choices=ALLOY_SHAPE_CHOICES)
    alloy_note = models.CharField(_("alloy_note"),max_length=150,null=True,blank=True)

    def __str__(self):
        return f"{_('alloy_id')} {self.alloy_id}"

    class Meta:
        verbose_name = _("alloy detail")
        verbose_name_plural = _("alloy details")

class AppPrepareGold(LoggingModel):
    STATE_DRAFT = 1

gold_travel/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from gold_travel.models import TblStateRepresentative

UserModel = get_user_model()

class TblStateRepresentativeForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=UserModel.objects.filter(groups__name__in=('gold_travel_state','gold_travel_ssmo')), label=_("user"))
    # def __init__(self, *args, **kwargs):        
    #     super().__init__(*args, **kwargs)

    class Meta:
        model = TblStateRepresentative    
        fields = ["user","name","state","authority"] 

gold_travel/templates/gold_travel/gold_travel.html
{% extends 'gold_travel/report_base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load auth_extras %}
{% load static  %}
{% load humanize %}
{% block content %}
  <div style="text-align:left">{{object.code}}</div>
  <center>
    <h3 style="font-weight: bold !important;text-decoration: underline !important;">
{%if object.form_type == 1 %}
    إستمارة ترحيل ونقل لأغراض صادر الذهب
    {% comment %} إستمارة ترحيل ونقل لأغراض بيع الذهب {% endcomment %}
    {%if object.state == 1 %}
        &nbsp;(مسودة)
    {%endif%}
{% elif object.form_type == 2 %}
    إستمارة تصدير ذهب بغرض التصنيع وإعادة التصنيع
    {%if object.state == 1 %}
        &nbsp;(مسودة)
    {%endif%}
{% elif object.form_type == 3 %}
    إستمارة ترحيل ونقل لأغراض صادر الفضة
    {%if object.state == 1 %}
        &nbsp;(مسودة)
    {%endif%}
{%endif%}
    </h3>
  </center>
  
  <br/>

  <div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th width="15%" class="active">التاريخ</th>
            <td>{{object.date|date:"Y/m/d"}}م</td>
            <th width="15%" class="active">الوجهة</th>
            <td>{{object.get_destination_display}}</td>
        </tr>
        <tr>
            <th width="15%" class="active">اسم المالك</th>
            <td>{{object.owner_name}}</td>
            <th width="15%" class="active">العنوان</th>
            <td>{{object.owner_address}}</td>
        </tr>
        <tr>
            <th width="15%" class="active">اسم الناقل</th>
            <td>{{object.repr_name}}</td>
            <th width="15%" class="active">العنوان ورقم الهاتف</th>
            <td>{{object.repr_address}} - {{object.repr_phone}}</td>
        </tr>
        <tr>
            <th width="15%" class="active">إثبات الهوية</th>
            <td>{{object.get_repr_identity_type_display}} {{object.repr_identity}}</td>
            <th width="15%" class="active">الإصدار</th>
            <td>{{object.repr_identity_issue_date|date:"Y/m/d"}}م</td>
        </tr>
        <tr>
            <th width="15%" class="active">وزن الخام المنقول</th>
            <td>{{object.gold_weight_in_gram|intcomma}} جرام</td>
            <th width="15%" class="active">عدد السبائك</th>
            <td>{{object.gold_alloy_count}}</td>
        </tr>
        <tr>
            <th width="15%" class="active">وصف المنقول</th>
            <td colspan="3">{{object.gold_description}}</td>
        </tr>
    </table>
</div>

  <h4>الإعتماد:</h4>
  {% with has_astikhbarat=request.user.state_representative.state.state_gold_travel.has_2lestikhbarat_2l3askria %}
  <div class="table-responsive">
    <table class="table table-bordered">
        <tr class="active">
            <th>البيان</th>
            <th {% if has_astikhbarat %} width="23%" {% else %} width="30%" {% endif %}>ممثل الشركة السودانية للموارد المعدنية المحدودة</th>
            <th {% if has_astikhbarat %} width="23%" {% else %} width="30%" {% endif %}>ممثل أمن إقتصاديات المعادن</th>
            <th {% if has_astikhbarat %} width="23%" {% else %} width="30%" {% endif %}>ممثل شرطة تأمين التعدين</th>
            {% if has_astikhbarat %}
            <th width="23%">ممثل هيئة الإستخبارات العسكرية</th>
            {% endif %}
        </tr>
        <tr>
            <th height="30px" class="active">الإسم</th>
            <td height="30px">{% if state_repr.2 %} {{state_repr.2}} {% endif %}</td>
            <td height="30px">{% if state_repr.3 %} {{state_repr.3}} {% endif %}</td>
            <td height="30px">{% if state_repr.4 %} {{state_repr.4}} {% endif %}</td>
            {% if has_astikhbarat %}
            <td height="30px">{% if state_repr.5 %} {{state_repr.5}} {% endif %}</td>
            {% endif %}
        </tr>
        <tr>
            <th height="30px" class="active">التوقيع</th>
            <td height="30px">&nbsp;</td>
            <td height="30px">&nbsp;</td>
            <td height="30px">&nbsp;</td>
            {% if has_astikhbarat %}
            <td height="30px">&nbsp;</td>
            {% endif %}
        </tr>
        <tr>
            <th height="80px" class="active">الختم</th>
            <td height="80px">&nbsp;</td>
            <td height="80px">&nbsp;</td>
            <td height="80px">&nbsp;</td>
            {% if has_astikhbarat %}
            <td height="80px">&nbsp;</td>
            {% endif %}
        </tr>

    </table>
  </div>
    {% endwith %}
    <p>تنبيهات هامة:</p>
    <ol>
        <li>مدة سريان الإستمارة ثلاثة أيام عمل رسمية.</li>
        <li>أي تعديل أو كشط يلغي الإستمارة.</li>
        <li>يسلم إيصال الإيداع الصادر من المواصفات والمقاييس إلى الشركة السودانية للموارد المعدنية المحدودة خلال المدة اعلاه.</li>
        {%if object.form_type == 1 %}
        <li>هذه الإستمارة صادرة لأغراض ترحيل الذهب ولأغراض الصادر فقط.</li>
        {%elif object.form_type == 2 %}
        <li>هذه الإستمارة صادرة لأغراض ترحيل الذهب ولأغراض الصادر فقط.</li>
        {%elif object.form_type == 3 %}
        <li>هذه الإستمارة صادرة لأغراض ترحيل الفضة ولأغراض الصادر فقط.</li>
        {%endif %}

        {% if object.form_type != 2 %}
        <li>هذه الإستمارة مجانية.</li>
        {%endif %}

    </ol>

    <div style="page-break-after: always;"></div>
    <br/>
    <image src="{% static 'gold_travel/img/logo.png'%}" class="center"/>

    <h4 style="text-align:center">الإدارة العامة للرقابة والإشراف على شركات الصادر وأسواق الذهب</h4>
    <h4 style="text-align:center">إدارة أسواق الذهب ولاية {{request.user.state_representative.state}}</h4>
    <h4 style="text-align:center">مرفق إستمارة رقم ({{object.code}})</h4>
    <h4 style="text-align:center">وزن السبائك بالتفاصيل</h4>

    {% for chunk in alloy_chunks%}

    {% if forloop.counter > 1 %}
        <div style="page-break-after: always;"></div>
        <br/>
        <image src="{% static 'gold_travel/img/logo.png'%}" class="center"/>
        <br/>
    {%endif%}

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="active">رقم السبيكة</th>
                    <th class="active">الوزن بالجرام</th>
                    <th class="active">ملاحظات</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in chunk%}
                <tr>
                    <td>{{obj.alloy_id}}</td>
                    <td>{{obj.alloy_weight_in_gram|intcomma}}</td>
                    <td>{{obj.get_alloy_shape_display}} {%if obj.alloy_note%} - {{obj.alloy_note}} {% endif%}</td>
                </tr>
                {% endfor %}

                {% if forloop.last %}
                <tr>
                    <th class="active">المجموع الكلي</th>
                    <th class="active">{{object.gold_weight_in_gram|intcomma}}</th>
                    <th class="active">&nbsp;</th>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <h4>الإعتماد: ..........................</h4>

    {% endfor %}

  
{% endblock content %}

gold_travel/templates/gold_travel/whom_may_concern.html
{% extends 'gold_travel/report_base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load auth_extras %}
{% load humanize %}

{% block content %}
  التاريخ: {{object.date|date:"Y/m/d"}}م
  <br/>
  <br/>
  <center>
    <p style="font-weight: bold !important;text-decoration: underline !important;">
    شهادة لمن يهمه الأمر
    {%if object.state == 1 %}
  &nbsp;(مسودة)
    {%endif%}
    </p>
  </center>
  <br/>
  <br/>

  تشهد الشركة السودانية للموارد المعدنية بأن  <b>{{object.owner_name}}</b> بصدد شراء وسبك وتجهيز  كمية ذهب في حدود <b>{{object.gold_weight_in_gram|intcomma}} جرام</b> وفق مواصفات الهيئة السودانية للمواصفات والمقاييس، بعيارات مختلفة وستتابع الشركة السودانية للموارد المعدنية المحدودة الاجراءات اللازمة لحين اصدار استمارة ترحيل بغرض الصادر وأن هذه الشهادة مبرئة للذمة في مراحل الشراء والسبك والتجهيز.

  <br/><br/>
  {% comment %} <center> {% endcomment %}
  وهذا منا للعلم ...........................
  {% comment %} </center> {% endcomment %}

  <br/><br/>

  <b>تنبيه مهم:</b> هذه الشهادة تسري <b>لمدة اسبوعين فقط</b> ولغرض الشراء والسبك والتجهيز.

  <br/><br/>
  <br/><br/>
  <br/><br/>

  <div style="text-align:left">
  {{object.issuer.name}}
  <br/>
  رئيس قسم اسواق الذهب بولاية {{object.issuer.state}}
  </div>

{% endblock content %}